name: Checks

on:
  push:

jobs:
  checks:
    name: Repo checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install prek
        uses: taiki-e/install-action@v2
        with:
          tool: prek

      - name: Run checks
        run: prek . --all-files --skip no-commit-to-branch
