name: Ingest checks

on:
  push:
    paths:
      - "ingest/**"

jobs:
  ingest:
    name: Ingest checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        working-directory: ingest
        run: uv sync --dev

      - name: Run tests
        run: make ingest-tests
